apiVersion: v1
kind: Secret
metadata:
  name: ${PROJECT_NAME}-secret
type: Opaque
stringData:
  postgres-user: dog
  postgres-password: q1w2e3r4
  postgres-db: dogdb
  chatify-user: cat
  chatify-password: q1w2e3r4
  chatify-db: catdb
