import type { Metadata } from "next";
import { notoSansKr, notoSerifKr } from "@/app/styles/fonts";
import Layout from "@/components/layout/Layout";
import { Providers } from "@/utils/Providers";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${notoSansKr.className} ${notoSerifKr.variable} antialiased text-slate-950 lg:bg-slate-100 dark:bg-slate-950 dark:text-white`}
      >
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
